name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Push de l'image Docker sur DockerHub ou sur un registre
      - name: Push Docker image to DockerHub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag myapp:latest $DOCKER_USERNAME/myapp:latest
          docker push $DOCKER_USERNAME/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Vérifie le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Déployer avec kubectl (à adapter pour ton environnement)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # Appliquer la configuration Kubernetes
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
